# Generated by Django 6.0.7 on 2026-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0004_incrementcycleskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementrequest',
            name='manager_rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
