# Generated by Django 6.0.7 on 2026-08-01 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0005_incrementrequest_manager_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementrequest',
            name='ceo_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='ceo_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_ceo_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='ceo_final_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='ceo_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='hr_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='hr_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_hr_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='hr_suggested_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='performance_report',
            field=models.TextField(blank=True, help_text="Manager's written performance report."),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='report_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incrementrequest',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incrementrequest',
            name='requested_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incrementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_REPORT', 'Report Requested from Manager'), ('PENDING_HR_REVIEW', 'Report Submitted — Pending HR Review'), ('PENDING_CEO', 'Pending CEO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
