# Generated by Django 6.0.7 on 2026-08-02 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0006_incrementrequest_ceo_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='hr_reviewed_at',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='ceo_final_percent',
            new_name='ceo_percent',
        ),
        migrations.RemoveField(
            model_name='incrementrequest',
            name='hr_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='incrementrequest',
            name='hr_suggested_percent',
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='ceo_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_forwarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='hr_notes',
            field=models.TextField(blank=True, help_text="HR's notes/analysis sent along to the CEO."),
        ),
        migrations.AlterField(
            model_name='incrementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_REPORT', 'Report Requested from Manager'), ('REPORT_SUBMITTED', 'Report Submitted — Pending HR Review'), ('PENDING_CEO', 'Forwarded to CEO for Decision'), ('CEO_DECIDED', 'CEO Gave Percentage — Pending Salary Update'), ('APPLIED', 'Salary Updated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
