# Generated by Django 6.0.7 on 2026-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0007_rename_hr_reviewed_at_incrementrequest_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementfeedback',
            name='suggested_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Manager's suggested increment percentage.", max_digits=6, null=True),
        ),
    ]
