# Generated by Django 6.0.7 on 2026-08-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0008_incrementfeedback_suggested_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementfeedback',
            name='report_file',
            field=models.FileField(blank=True, help_text='Performance report (docx/xlsx/pdf) uploaded by the manager.', null=True, upload_to='increment_reports/'),
        ),
        migrations.AlterField(
            model_name='incrementfeedback',
            name='suggestion',
            field=models.CharField(blank=True, choices=[('SUGGEST', 'Yeah! I suggest increment for this employee'), ('NEUTRAL', 'My suggestion is neutral, this is working normal'), ('NOT_SUGGEST', "No, I don't suggest — not working hard")], max_length=15),
        ),
    ]
