# Generated by Django 6.0.7 on 2026-08-03 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0009_incrementfeedback_report_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='ceo_comment',
            new_name='coo_comment',
        ),
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='ceo_decided_at',
            new_name='coo_decided_at',
        ),
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='ceo_percent',
            new_name='coo_percent',
        ),
        migrations.RenameField(
            model_name='incrementrequest',
            old_name='ceo_rejection_reason',
            new_name='coo_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='incrementrequest',
            name='ceo_decided_by',
        ),
        migrations.AddField(
            model_name='incrementrequest',
            name='coo_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increments_coo_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incrementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_REPORT', 'Report Requested from Manager'), ('REPORT_SUBMITTED', 'Report Submitted — Pending HR Review'), ('PENDING_COO', 'Forwarded to COO for Decision'), ('COO_DECIDED', 'COO Gave Percentage — Pending Salary Update'), ('APPLIED', 'Salary Updated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
