# Generated by Django 6.0.7 on 2026-08-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0010_rename_ceo_comment_incrementrequest_coo_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CooReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='coo_reports/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coo_comment', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Optional — leave blank for a general report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coo_reports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coo_reports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
