# Generated by Django 6.0.7 on 2026-08-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('increments', '0011_cooreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooreport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='cooreport',
            name='coo_comment',
        ),
        migrations.RemoveField(
            model_name='cooreport',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='cooreport',
            name='status',
        ),
        migrations.AlterField(
            model_name='cooreport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coo_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cooreport',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
