# Generated by Django 6.0.7 on 2026-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeeprofile_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_card_received',
            field=models.BooleanField(blank=True, default=False, verbose_name='ID Card Received'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_pf_applicable',
            field=models.BooleanField(blank=True, default=True, verbose_name='PF Applicable'),
        ),
    ]
