# Generated by Django 6.0.7 on 2026-07-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_accessible_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['branch__name', 'name']},
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'branch')},
        ),
    ]
