# Generated by Django 6.0.7 on 2026-08-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('ADMIN', 'Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('GENERAL_MANAGER', 'General Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
