# Generated by Django 6.0.7 on 2026-08-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COO', 'COO'), ('ADMIN', 'Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('GENERAL_MANAGER', 'General Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
