# Generated by Django 6.0.7 on 2026-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_senior_hr',
            field=models.BooleanField(default=False),
        ),
    ]
