# Generated by Django 6.0.7 on 2026-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_is_senior_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COO', 'COO'), ('ADMIN', 'Admin'), ('SENIOR_HR', 'Senior HR'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('GENERAL_MANAGER', 'General Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
    ]
