# Generated by Django 6.0.7 on 2026-08-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_COO', 'Pending COO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HR_REJECTED_PENDING_MANAGER', 'HR Declined - Awaiting Manager')], default='PENDING_MANAGER', max_length=30),
        ),
    ]
