# Generated by Django 6.0.7 on 2026-07-25 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_monthlyattendancesheet_cl_quota_override_and_more'),
        ('core', '0006_user_accessible_branches'),
        ('projects', '0004_project_completed_at_project_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_type', models.CharField(choices=[('OT', 'Overtime'), ('SUNDAY', 'Sunday'), ('HOLIDAY', 'Holiday')], default='OT', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Verification'), ('APPROVED', 'Approved'), ('REJECTED_MANAGER', 'Rejected by Manager'), ('REJECTED_HR', 'Rejected by HR')], default='PENDING_MANAGER', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comment', models.CharField(blank=True, max_length=255)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='projects.project')),
                ('reviewed_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_hr_reviewed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_manager_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
