# Generated by Django 6.0.7 on 2026-08-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_overtimerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED_MANAGER', 'Rejected by Manager'), ('REJECTED_HR', 'Rejected by HR')], default='PENDING_MANAGER', max_length=20),
        ),
    ]
